categories = {
    "Countries": ['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia',
                  'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
                  'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria',
                  'Burkina Faso', 'Burundi', "Ivory Coast", 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic',
                  'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
                  'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
                  'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia',
                  'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
                  'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
                  'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
                  'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia',
                  'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova',
                  'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
                  'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
                  'Palau', 'Palestine State', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
                  'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines',
                  'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone',
                  'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan',
                  'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan', 'Tanzania',
                  'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
                  'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States of America', 'Uruguay', 'Uzbekistan',
                  'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'],
    "Movies": ['The Shawshank Redemption', 'The Godfather', 'The Godfather: Part II', 'The Dark Knight', '12 Angry Men', "Schindler's List",
               'The Lord of the Rings: The Return of the King', 'Pulp Fiction', 'The Good, the Bad and the Ugly', 'Fight Club',
               'The Lord of the Rings: The Fellowship of the Ring', 'Forrest Gump', 'Inception', 'Star Wars: Episode V - The Empire Strikes Back',
               'The Lord of the Rings: The Two Towers', "One Flew Over the Cuckoo's Nest", 'Goodfellas', 'The Matrix', 'Seven Samurai',
               'Avengers: Endgame', 'Se7en', 'City of God', 'Star Wars: Episode IV - A New Hope', 'The Silence of the Lambs',
               "It's a Wonderful Life", 'Life Is Beautiful', 'Spirited Away', 'Saving Private Ryan', 'The Usual Suspects', 'Léon: The Professional',
               'The Green Mile', 'Interstellar', 'Psycho', 'American History X', 'City Lights', 'Casablanca', 'Once Upon a Time in the West',
               'The Pianist', 'Modern Times', 'The Intouchables', 'The Departed', 'Back to the Future', 'Terminator 2: Judgment Day', 'The Lion King',
               'Whiplash', 'Rear Window', 'Gladiator', 'Raiders of the Lost Ark', 'The Prestige', 'Apocalypse Now', 'Memento', 'Alien',
               'Grave of the Fireflies', 'Cinema Paradiso', 'The Great Dictator', 'Spider-Man: Into the Spider-Verse', 'Sunset Boulevard',
               'The Lives of Others', 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'Avengers: Infinity War',
               'Paths of Glory', 'Django Unchained', 'The Shining', 'WALL-E', 'Princess Mononoke', 'Witness for the Prosecution', 'Oldboy',
               'The Dark Knight Rises', 'Aliens', 'American Beauty', 'Once Upon a Time in America', 'Coco', 'Das Boot', 'Citizen Kane', 'Braveheart',
               'Vertigo', 'Your Name', 'North by Northwest', 'Reservoir Dogs', 'Star Wars: Episode VI - Return of the Jedi', 'Amadeus', 'M',
               'Requiem for a Dream', 'Toy Story', '3 Idiots', 'Dangal', '2001: A Space Odyssey', 'Eternal Sunshine of the Spotless Mind',
               'Like Stars on Earth', 'Lawrence of Arabia', 'A Clockwork Orange', "Singin' in the Rain", 'Inglourious Basterds', 'Amélie',
               'Double Indemnity', 'Taxi Driver', 'Full Metal Jacket', 'Good Will Hunting', 'Bicycle Thieves', 'To Kill a Mockingbird'],
    "All": [],
}